In [1]:
# Import the library of Pandas.
import pandas as pd

In [2]:
# Read The path of Excel file and save it in a variable called (df) --> it means DataFrame.
df = pd.read_excel(r"C:\Users\Classic\Desktop\data_all.xltx", engine="openpyxl")

In [3]:
# Transform suffix from xltx to csv.
df.to_csv(r"C:\Users\Classic\Desktop\data_all.csv", index=False, encoding="utf-8-sig")

In [4]:
# Know the numbers of rows and columns.
df.shape

(259917, 10)

In [5]:
# Show columns
df.columns

Index(['account_id', 'SourceSystem', 'activity_date', 'who_id',
       'opportunity_id', 'opportunity_stage', 'is_lead', 'types', 'Country',
       'solution'],
      dtype='object')

In [6]:
# Know The information for this file.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 259917 entries, 0 to 259916
Data columns (total 10 columns):
 #   Column             Non-Null Count   Dtype         
---  ------             --------------   -----         
 0   account_id         259917 non-null  object        
 1   SourceSystem       259917 non-null  object        
 2   activity_date      205516 non-null  datetime64[ns]
 3   who_id             238294 non-null  object        
 4   opportunity_id     45849 non-null   object        
 5   opportunity_stage  259901 non-null  object        
 6   is_lead            259901 non-null  float64       
 7   types              259901 non-null  object        
 8   Country            259730 non-null  object        
 9   solution           259901 non-null  object        
dtypes: datetime64[ns](1), float64(1), object(8)
memory usage: 19.8+ MB


In [7]:
# Show the total of all null rows.
df.isna().sum()

account_id                0
SourceSystem              0
activity_date         54401
who_id                21623
opportunity_id       214068
opportunity_stage        16
is_lead                  16
types                    16
Country                 187
solution                 16
dtype: int64

In [8]:
# Show the account_id column.
df['account_id']

0         0010L00001hVmFhQAK
1         0010L00001hVmFhQAK
2         0010L00001hVmFhQAK
3         0010L00001hVmFhQAK
4         0010L00001hVmFhQAK
                 ...        
259912    001b00000424wsfAAA
259913    001b00000424wsfAAA
259914    001b00000424wsfAAA
259915    001b000004275jgAAA
259916    001b000004275jgAAA
Name: account_id, Length: 259917, dtype: object

In [9]:
# Show all unique data in account_id column.
df['account_id'].unique()

array(['0010L00001hVmFhQAK', '0010L00001hVxd6QAC', '0010L00001hVyJQQA0',
       ..., '001b0000040UoFUAA0', '001b00000424wsfAAA',
       '001b000004275jgAAA'], dtype=object)

In [10]:
# Show min & median & max length of all datas in account_id column.
lengths = df['account_id'].astype(str).str.len()
([lengths.min(), lengths.median(), lengths.max()])

[18, 18.0, 18]

In [11]:
# Show all unique data in SourceSystem column.
df['SourceSystem'].unique()

array(['SFDC_US', 'SFDC_ROW', 'SFDC_BEANWORKS', 'SFDC_CXM', 'SFDC_PP',
       'SFDC_GLOBAL'], dtype=object)

In [12]:
# Show the total of all null rows.
df['SourceSystem'].isna().sum()

np.int64(0)

In [13]:
# Show all unique data in activity_date column.
df['activity_date'].unique()

<DatetimeArray>
['2022-07-25 00:00:00', '2023-02-08 00:00:00', '2023-02-14 00:00:00',
 '2023-02-20 00:00:00', '2023-03-16 00:00:00', '2023-03-22 00:00:00',
 '2023-12-04 00:00:00', '2024-02-12 00:00:00', '2024-02-22 00:00:00',
 '2024-04-01 00:00:00',
 ...
 '2024-09-26 22:00:00', '2024-10-14 22:00:00', '2024-11-25 23:00:00',
 '2023-04-28 00:00:00', '2025-04-16 22:00:00', '2025-05-18 22:00:00',
 '2024-10-10 22:00:00', '2024-10-20 22:00:00', '2024-11-27 23:00:00',
 '2025-02-04 23:00:00']
Length: 4719, dtype: datetime64[ns]

In [14]:
# Show the total of all null rows.
df['activity_date'].isna().sum()

np.int64(54401)

In [15]:
# Transform dataType into datetime.
df['activity_date'] = pd.to_datetime(df['activity_date'], errors = 'coerce')

In [16]:
# Arrange the columns by account_id and activity_date columns.
df = df.sort_values(by=['account_id', 'activity_date'], ascending = True)

In [17]:
# Show DataFrame after arranging the columns.
df

account_id SourceSystem activity_date              who_id  \
0       0010L00001hVmFhQAK      SFDC_US    2022-07-25  0030L00001vlbHLQAY   
1       0010L00001hVmFhQAK      SFDC_US    2023-02-08  0034X00002xZlQtQAK   
2       0010L00001hVmFhQAK      SFDC_US    2023-02-14  0030L00001vlbHLQAY   
3       0010L00001hVmFhQAK      SFDC_US    2023-02-20  0030L00001vlbHLQAY   
4       0010L00001hVmFhQAK      SFDC_US    2023-03-16  0034X00003GOUrFQAX   
...                    ...          ...           ...                 ...   
259912  001b00000424wsfAAA     SFDC_ROW    2025-05-15  0030X00002gQd41QAC   
259913  001b00000424wsfAAA     SFDC_ROW    2025-05-15  0030X00002gQd41QAC   
259914  001b00000424wsfAAA     SFDC_ROW    2025-07-03  003SZ00000bQOHfYAO   
259915  001b000004275jgAAA     SFDC_ROW    2022-11-16  0036700003ycNNIAA2   
259916  001b000004275jgAAA     SFDC_ROW    2022-11-17  003b00000206ARZAA2   

       opportunity_id opportunity_stage  is_lead         types Country  \
0                 NaN            no_opp      1.0     Follow Up      US   
1                 NaN            no_opp      1.0  Inbound Call      US   
2                 NaN            no_opp      1.0  Inbound Call      US   
3                 NaN            no_opp      2.0  Inbound Call      US   
4                 NaN            no_opp      1.0  Inbound Call      US   
...               ...               ...      ...           ...     ...   
259912            NaN            no_opp      1.0          Call      FR   
259913            NaN            no_opp      2.0          Call      FR   
259914            NaN            no_opp      1.0         Email      FR   
259915            NaN            no_opp      1.0          Call      FR   
259916            NaN            no_opp      1.0          Call      FR   

       solution  
0           MRS  
1           MRS  
2           MRS  
3           MRS  
4           MRS  
...         ...  
259912      MRS  
259913      MRS  
259914      MRS  
259915      MRS  
259916      MRS  

[259917 rows x 10 columns]

In [18]:
# Show all unique data in who_id column.
df['who_id'].unique()

array(['0030L00001vlbHLQAY', '0034X00002xZlQtQAK', '0034X00003GOUrFQAX',
       ..., '003SZ00000bQOHfYAO', '0036700003ycNNIAA2',
       '003b00000206ARZAA2'], dtype=object)

In [19]:
# Show the total of all null rows.
df['who_id'].isna().sum()

np.int64(21623)

In [20]:
# Show all unique data in opportunity_id column.
df['opportunity_id'].unique()

array([nan, '0060y000019Fk7PAAS', '0060y00001F66cvAAB', ...,
       '0060X00000ei1t9QAA', '0066700000znDK2AAM', '0066700000wUXg9AAG'],
      dtype=object)

In [21]:
# Show the total of all null rows.
df['opportunity_id'].isna().sum()

np.int64(214068)

In [22]:
# Show all unique data in opportunity_stage column.
df['opportunity_stage'].unique()

array(['no_opp', 'Won', 'Lost', 'Diagnose', 'Access', 'Discovery',
       'Negotiate', 'Delivery', 'Design', '01 - New',
       'SDS - 05 - Negotiating', 'Implemented', '2 - Validation',
       '8 - Disqualified', 'Stage 2: Qualified Renewal',
       '1 - Qualification​', '3 - Design',
       'Stage 5: Procurement/Negotiation',
       'Stage 8: €0 Contract Change', '4 - Negotiate', nan,
       '5 - Procurement', '05 - Negotiating', '03 - Qualified',
       '04 - Offer'], dtype=object)

In [23]:
# Show the total of all null rows.
df['opportunity_stage'].isna().sum()

np.int64(16)

In [24]:
# Modifying the data of opportunity_stage column and remove spaces and transform into UpperCase Characters.
df['opportunity_stage'] = df['opportunity_stage'].replace(['nan', None, ''], 'UNKNOWN')
df['opportunity_stage'] = df['opportunity_stage'].astype(str).str.strip().str.upper()

In [25]:
# Show all unique data in opportunity_stage column after modifying.
df['opportunity_stage'].unique()

array(['NO_OPP', 'WON', 'LOST', 'DIAGNOSE', 'ACCESS', 'DISCOVERY',
       'NEGOTIATE', 'DELIVERY', 'DESIGN', '01 - NEW',
       'SDS - 05 - NEGOTIATING', 'IMPLEMENTED', '2 - VALIDATION',
       '8 - DISQUALIFIED', 'STAGE 2: QUALIFIED RENEWAL',
       '1 - QUALIFICATION€‹', '3 - DESIGN',
       'STAGE 5: PROCUREMENT/NEGOTIATION',
       'STAGE 8: ‚¬0 CONTRACT CHANGE', '4 - NEGOTIATE', 'UNKNOWN',
       '5 - PROCUREMENT', '05 - NEGOTIATING', '03 - QUALIFIED',
       '04 - OFFER'], dtype=object)

In [26]:
# Modifying Two value of data in opportunity_stage column to make them without symbols and more beautiful.
df['opportunity_stage'] = df['opportunity_stage'].replace({
    '1 - QUALIFICATION€‹': '1 - QUALIFICATION',
    'STAGE 8: ‚¬0 CONTRACT CHANGE': 'STAGE 8: CONTRACT CHANGE'
})

In [27]:
# Show all unique data in opportunity_stage column after final modifying.
df['opportunity_stage'].unique()

array(['NO_OPP', 'WON', 'LOST', 'DIAGNOSE', 'ACCESS', 'DISCOVERY',
       'NEGOTIATE', 'DELIVERY', 'DESIGN', '01 - NEW',
       'SDS - 05 - NEGOTIATING', 'IMPLEMENTED', '2 - VALIDATION',
       '8 - DISQUALIFIED', 'STAGE 2: QUALIFIED RENEWAL',
       '1 - QUALIFICATION', '3 - DESIGN',
       'STAGE 5: PROCUREMENT/NEGOTIATION', 'STAGE 8: CONTRACT CHANGE',
       '4 - NEGOTIATE', 'UNKNOWN', '5 - PROCUREMENT', '05 - NEGOTIATING',
       '03 - QUALIFIED', '04 - OFFER'], dtype=object)

In [28]:
# Show all unique data in is_lead column.
df['is_lead'].unique()

array([ 1.,  2., nan])

In [29]:
# Show the total of all null rows.
df['is_lead'].isna().sum()

np.int64(16)

In [30]:
# Input 0 in the null rows.
df['is_lead'] = df['is_lead'].fillna(0)

In [31]:
# Show all unique data in is_lead column after modifying.
df['is_lead'].unique()

array([1., 2., 0.])

In [32]:
# Show the total of all null rows.
df['is_lead'].isna().sum()

np.int64(0)

In [33]:
# Show all unique data in types column.
df['types'].unique()

array(['Follow Up', 'Inbound Call', 'Meeting', 'Review', 'Email',
       'On-Site', 'Demo', 'Call', 'Discovery', 'Outbound Call',
       '2nd Appointment', '1st Appointment', nan], dtype=object)

In [34]:
# Modifying Two value of data in types column to make them more beautiful.
df['types'] = df['types'].replace({
    '1st Appointment':'First Appointment',
    '2nd Appointment': 'Second Appointment'
})

In [35]:
# Show all unique data in types column after modifying.
df['types'].unique()

array(['Follow Up', 'Inbound Call', 'Meeting', 'Review', 'Email',
       'On-Site', 'Demo', 'Call', 'Discovery', 'Outbound Call',
       'Second Appointment', 'First Appointment', nan], dtype=object)

In [36]:
# Show the total of all null rows.
df['types'].isna().sum()

np.int64(16)

In [37]:
# Show all unique data in Country column.
df['Country'].unique()

array(['US', 'FR', 'Martinique', 'Guyane Franأ§aise', nan, 'CA',
       'Thailand', 'Brazil', 'DE', 'Bulgaria', 'Ireland', 'Nicaragua',
       'Mexico', 'Spain', 'BE', 'Italy', 'Netherlands', 'Switzerland',
       'Poland', 'UK', 'Slovakia', 'Czech Republic', 'Austria',
       'Hong Kong', 'China', 'Japan', 'Taiwan', 'Australia',
       'Cayman Islands', 'India', 'New Zealand', 'Korea, Republic of',
       'Saudi Arabia', 'Malaysia', 'United Arab Emirates', 'Hungary',
       'Singapore', 'Latvia', 'Argentina', 'Israel', 'Turkey', 'Peru',
       'South Africa', 'El Salvador', '[NULL]', 'NL', 'AT', 'IT', 'DK',
       'LU', 'CH', 'IE', 'Denmark', 'Rأ©union', 'Guadeloupe'],
      dtype=object)

In [38]:
# Modifying All null and duplicate data and make data more readable.
df['Country'] = df['Country'].replace(
    {
        '[NULL]':'Unknown',
         None: 'Unknown',
        'Guyane Franأ§aise':'French Guiana',
        'Rأ©union':'Reunion',
        'NL':'Netherlands',
        'AT':'Austria',
        'CH':'Switzerland',
        'IT':'Italy',
        'DK':'Denmark',
        'IE':'Ireland',
        'US': 'United States',
        'FR': 'France',
        'CA': 'Canada',
        'DE': 'Germany',
        'BE': 'Belgium',
        'UK': 'United Kingdom',
        'LU': 'Luxembourg',
        'Israel':'Palestine'
    }
)

In [39]:
# Show all unique data in Country column after modifying.
df['Country'].unique()

array(['United States', 'France', 'Martinique', 'French Guiana',
       'Unknown', 'Canada', 'Thailand', 'Brazil', 'Germany', 'Bulgaria',
       'Ireland', 'Nicaragua', 'Mexico', 'Spain', 'Belgium', 'Italy',
       'Netherlands', 'Switzerland', 'Poland', 'United Kingdom',
       'Slovakia', 'Czech Republic', 'Austria', 'Hong Kong', 'China',
       'Japan', 'Taiwan', 'Australia', 'Cayman Islands', 'India',
       'New Zealand', 'Korea, Republic of', 'Saudi Arabia', 'Malaysia',
       'United Arab Emirates', 'Hungary', 'Singapore', 'Latvia',
       'Argentina', 'Palestine', 'Turkey', 'Peru', 'South Africa',
       'El Salvador', 'Denmark', 'Luxembourg', 'Reunion', 'Guadeloupe'],
      dtype=object)

In [40]:
# Show the total of all null rows in Country column.
df[df['Country'] == 'Unknown'].shape[0]

301

In [41]:
# Show all unique data in solution column.
df['solution'].unique()

array(['MRS', 'Digital', 'PLS', nan], dtype=object)

In [42]:
# Show the total of all null rows.
df['solution'].isna().sum()

np.int64(16)

In [43]:
# Remove all dulicates data in all columns.
df = df.drop_duplicates(subset = ['account_id', 'SourceSystem', 'activity_date', 'who_id',
       'opportunity_id', 'opportunity_stage', 'is_lead', 'types', 'Country',
       'solution'], keep = 'first')

In [48]:
# Remove all dulicates data in the more important columns.
df = df.drop_duplicates(subset = ['account_id', 'activity_date', 'types', 'Country',
       'solution'], keep = 'first')

In [53]:
# Remove all dulicates data in the important columns.
df = df.drop_duplicates(subset = ['account_id', 'activity_date', 'types'], keep = 'first')

In [60]:
# Show the total of all null rows.
df['solution'].isna().sum()

np.int64(0)

In [61]:
# Show the total of all null rows.
df['types'].isna().sum()

np.int64(0)

In [62]:
# Show the total of all null rows.
df['activity_date'].isna().sum()

np.int64(0)

In [63]:
# Show the total of all null rows in Country column.
df[df['Country'] == 'Unknown'].shape[0]

0

In [58]:
# Remove all null data in activity_date column.
df = df.dropna(subset=['activity_date'])

In [59]:
# Remove all Unknown data in Country column.
df = df.drop(df[df['Country'] == 'Unknown'].index)

In [64]:
# Show the numbers of rows after cleaning data.
df.shape

(154638, 10)

In [66]:
# Transform this file into Excel file 
df.to_excel("data_clean.xlsx", index= False)